# Generated by Django 5.1.5 on 2025-03-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=252, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
