# Generated by Django 5.1.5 on 2025-02-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadView',
            new_name='ModUpload',
        ),
    ]
