# Generated by Django 5.1.5 on 2025-02-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_rename_uploadview_modupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModUpload',
            new_name='ModList',
        ),
    ]
