# Generated by Django 5.1.5 on 2025-02-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0005_game_modlist_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
