# Generated by Django 5.1.5 on 2025-02-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0007_modlist_modtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modlist',
            name='modtags',
        ),
        migrations.AddField(
            model_name='modlist',
            name='modtags',
            field=models.BooleanField(blank=True, null=True, verbose_name='ModTag'),
        ),
    ]
