# Generated by Django 5.1.5 on 2025-02-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0008_remove_modlist_modtags_modlist_modtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modlist',
            name='modtags',
        ),
        migrations.AddField(
            model_name='modlist',
            name='modtags',
            field=models.ManyToManyField(blank=True, to='mods.modtag'),
        ),
    ]
