# Generated by Django 5.1.5 on 2025-02-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0009_remove_modlist_modtags_modlist_modtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModList',
            new_name='Mod',
        ),
    ]
