# Generated by Django 5.1.5 on 2025-02-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0010_rename_modlist_mod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.CreateModel(
            name='ModImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/uploads')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mods.mod')),
            ],
        ),
    ]
