# Generated by Django 5.1.5 on 2025-02-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0011_rename_image_mod_cover_image_modimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modimage',
            name='image',
        ),
        migrations.AddField(
            model_name='modimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='mod_images/'),
        ),
    ]
