# Generated by Django 5.1.5 on 2025-02-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0012_remove_modimage_image_modimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modimage',
            old_name='images',
            new_name='image',
        ),
    ]
