# Generated by Django 5.1.5 on 2025-03-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0015_mod_author_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='mod',
        ),
    ]
