# Generated by Django 5.1.5 on 2025-03-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0018_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
